port: 8080

jwt:
  secret_key: "secret_key"

database:
  host: "localhost"
  port: 5432
  dbname: "radio"
  user: "miha3009"
  password: "password"

email:
    from: "inbox@netradio.com"
    user: "fc48c3918d5073"
    password: "89747df89e72fa"
    host: "sandbox.smtp.mailtrap.io"
    port: 2525
